
CREATE TABLE DEPT
       (DEPTNO INTEGER PRIMARY KEY,
        DNAME VARCHAR(14),
        LOC VARCHAR(13));

CREATE TABLE EMP
       (EMPNO INTEGER AUTO_INCREMENT PRIMARY KEY,
        ENAME VARCHAR(64),
        JOB VARCHAR(9),
        AGE INTEGER,
        SAL DECIMAL(7, 2),
        DEPTNO INTEGER, 
        FOREIGN KEY(DEPTNO) REFERENCES DEPT(DEPTNO));
 